sudo: required
services:
  - docker


before_install:
  - docker build -t kalitamih/git-docker-react-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true kalitamih/git-docker-react-travis npm run test -- --coverage

