 
sudo: required
services:
  - docker

before_install:
  - docker build -t kalitamih/git-docker-react-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true kalitamih/git-docker-react-travis npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "git-docker-react-travis"
  env: "GitDockerReactTravis-env"
  bucket_name: "elasticbeanstalk-us-west-2-831964246238"
  bucket_path: "git-docker-react-travis"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"


